### ISSUE TITLE
function names collide with variable names

### ISSUE THREAD

**Issue by cougarten** [sulami/literate-calc-mode.el#15]
Variable names that are sub-strings of functions destroy the functions.

![image](https://user-images.githubusercontent.com/7131556/98708046-01083300-2381-11eb-90c8-30b830ae905c.png)

```
= abs(-2)
ab = 3
= abs(-2)
```

I'd suggest an option to disable the short writing that omits the `*` character.

I'm not sure if the setting should be enabled or disabled by default:
- default omitting enabled: formulas omiting the char don't work as expected any more, but the error is obvious and easily fixed by adding the `*- 
- default omitting disabled: formulas work, but functions fail in odd looking ways. Harder to "debug" as a user.

Anyways, no critical bug. It's easily detected and worked around.

**Comment by sulami** [comment]
I'd argue that is working as intended, I think for most users rich variable names are more important than functions, and if they use functions they're probably aware that they shouldn't shadow the names.

**Comment by codemac** [comment]
In this case, ab is not "shadowing" abs, it's a substring. If I used a variable name `s` and then want to use `sqrt` I certainly wouldn't expect this:

```
s = 5 => s: 5
= sqrt(25) => 5 qrt(25)
```

If I do the following:
```
sqrt = 5 => sqrt: 5
= sqrt(25) => 125
```

That's more the behavior I expect - I explicitly overrode the name, the calc function is no longer available.
