### ISSUE TITLE
literate-calc-remove-results not working with negative results

### ISSUE THREAD

**Issue by dinkonin** [sulami/literate-calc-mode.el#16]
On emacs 28 (if that matters) the `literate-calc-remove-results` command does not work on results containing negative numbers like `= 1 - 2  => -1`.

**Comment by dinkonin** [comment]
After some investigation `(setq literate-calc--result " => \\(?:[_[:alnum:][:blank:]-]+: \\)?.[],.[_[:digit:][:blank:]]+$")` fixes the problem.I just added a dot `.` after the `?` in `?[],.[_[:digit:][:blank:]]+$")`.

Am I missing something i.e. what did I break? Also thanks for the cool package.

**Comment by sulami** [comment]
So this regexp is actually generated by

```emacs-lisp
(defconst literate-calc--result
  (rx " => "
      (opt (+ (any alphanumeric blank "-_")) ": ")
      (+ (any digit blank "._[,]"))
      line-end))
```

The extra period should probably not be there, but I'll have to do some regexp debugging to find out what's going wrong there.

Thanks for the report, I'm not using 28 myself!

**Comment by sulami** [comment]
Actually, just reading this back I'm realising where it probably needs to go:

```emacs-lisp
(defconst literate-calc--result
  (rx " => "
      (opt (+ (any alphanumeric blank "-_")) ": ")c
      (+ (any digit blank "-._[,]"))
      line-end))
```
