### ISSUE TITLE
Don't calc for org =emphasis= syntax

### ISSUE THREAD

**Issue by mankoff** [sulami/literate-calc-mode.el#3]
Stricter syntax requirements would be good to avoid treating =emphasis= highlights as calc statements. I see

    treat =emphasis= highlights `=> treat: emphasis`

**Comment by sulami** [comment]
Ken Mankoff <notifications@github.com> writes:

> Stricter syntax requirements would be good to avoid treating =emphasis= highlights as calc statements. I see
>
>     treat =emphasis= highlights `=> treat: emphasis`

That's a good spot, we can probably tighten the regexp to always read to
the end of the line and ensure there's no second `=` in there. I'll see
if I can get that in tomorrow.

-- 
Robin

**Comment by sulami** [comment]
I fixed your specific issue, but I noted that there is still a weird situation if you have a multi-line emphasis:

```
=this is a valid calc line
but also emphasis=
```

I'm not sure if/how I want to solve that at this point though.
