### ISSUE TITLE
function problem

### ISSUE THREAD

**Issue by hajovonta** [sulami/literate-calc-mode.el#31]
Hi,

tried to calculate the Greatest Common Divisor of two integers, and noticed this:

![image](https://user-images.githubusercontent.com/1049597/198201003-54c5967e-32e2-4768-a3bf-b712f005c4ae.png)

when I remove the comment from the third line:

![image](https://user-images.githubusercontent.com/1049597/198201088-4a8c24c7-eb26-4860-8659-f7778eb20076.png)

seems to be some parsing bug, can you please confirm?

**Comment by codemac** [comment]
this is the same as #15

**Comment by sulami** [comment]
Fixed in https://github.com/sulami/literate-calc-mode.el/commit/fb39084ae6bcfd28bc8f10c4b827fa226cda03b0.
