### ISSUE TITLE
Incorrect handling of complex units

### ISSUE THREAD

**Issue by karstenpatzwaldt** [sulami/literate-calc-mode.el#4]
Complex units are handled incorrectly, for example:

```
  Weight = 1.3oz/yd^2
  Area = 2m^2
  Total Weight = Weight * Area
```

Should result in `3.109 oz`, but actual output is `0.2166 oz / (d^2 m^2)`.

Note that the initial value is already incorrect, the first line shows `=> Weight: 0.4333 oz/d^2`.

As comparison, `(calc-eval "1.3oz/yd^2")` results in `1.3 oz / yd^2`, and `(calc-eval "(1.3oz/yd^2) * (2m^2)")` in `2.6 oz m^2 / yd^2`, which is correct.

**Comment by sulami** [comment]
I’ve got a hunch about that, will report back.

Thanks for reporting.

**Comment by dvzubarev** [comment]
Thank you for the fix, some problem still persists when invoking `literate-calc-insert-results` on this buffer
`Total Weight: 2.6 oz m^2 / yd^2` transforms to `Total Weight: 2 Weight m^2`.

Also slightly off topic question. How to use unit convert functions like `calc-simplify-units` or `calc-convert-units`?

**Comment by sulami** [comment]
dvzubarev <notifications@github.com> writes:

> Thank you for the fix, some problem still persists when invoking `literate-calc-insert-results` on this buffer
> `Total Weight: 2.6 oz m^2 / yd^2` transforms to `Total Weight: 2 Weight m^2`.
>
That is odd, as they use the same function for evaluation, but I'll have
a look.

> Also slightly off topic question. How to use unit convert functions like `calc-simplify-units` or `calc-convert-units`?
Use the respective algebraic function
(https://www.gnu.org/software/emacs/manual/html_node/calc/Function-Index.html).

So for example calc-simplify-units corresponds to usimplify:

= usimplify(1m + 3mm) => 1.003 m

I'll add a note in the readme for that.


-- 
Robin
