### ISSUE TITLE
Is there a way to always simplify units?

### ISSUE THREAD

**Issue by tad-lispy** [sulami/literate-calc-mode.el#41]
Hi! Thank you so much for Literate Calc Mode. It's very cool!

I started to use it to calculate service fees for my clients. Something like:

``` text
weeks = 5 days => weeks: 5 days

Contract duration = 5 weeks => Contract duration: 25 days
Time off = 3 days => Time off: 3 days
Work time = Contract duration - Time off => Work time: 22 days
Cost = 1000 EUR / days => Cost: 1,000 EUR / days
Fee = Cost * Work time => Fee: 22,000 EUR days / days
```

It's really nice to use multiple words for variables. Makes it much more suitable for non-technical recepients of my invoices. However the bottom line is not so nice when it comes to units (`EUR days / days`). It's possible to wrap it in `usimplify`, but then the calculation is not so friendly for non-programmers:

``` text
Fee = usimplify (Cost * Work time) => Fee: 22,000 EUR
```

Is there a way to always apply `usimplify` to the results? I tried to set the `calc-simplify-mode` to `units`, but it doesn't seem to have any effect.

``` emacs-lisp
(setq-local calc-simplify-mode 'units)
```

Related issue: https://github.com/sulami/literate-calc-mode.el/issues/27

Anyway, thank you so much!

**Comment by sulami** [comment]
Hey,

there's currently no simple way of automatically simplifying the results, but that should be easy to add as an option. I'll have a look at this over this weekend.

**Comment by sulami** [comment]
I've opted to add a simple (buffer-local) toggle for this, as I think this is a generally good idea. See the readme for instructions and let me know if that works for you.

**Comment by tad-lispy** [comment]
Brilliant. Thank you!
