### ISSUE TITLE
Customization options

### ISSUE THREAD

**Issue by mkarup** [sulami/literate-calc-mode.el#44]
At the moment, it looks like grouping of digits is hardcoded, would it be possible to have this as a customizable options?

Similarly, would it be possible to adjust the wordsize? I sometimes need to do some bitwise operations, and it seems like literate-calc-mode defaults to 32-bit words. 

If the above is already customizable, I apologize! (How would I then go about changing it?)

**Comment by sulami** [comment]
True, they are fixed, but it should be trivial to provide customization options.

Looking at it I'm actually thinking of adding the ability to add arbitrary options, instead of gradually duplicating all of calc's options.
