### ISSUE TITLE
`literate-calc-insert-results` insert partially evaluated results

### ISSUE THREAD

**Issue by mpereira** [sulami/literate-calc-mode.el#8]
Hi @sulami,

Thanks for writing this package! I'm using it to do end of the month finance stuff with my girlfriend 🙂 

I noticed that `literate-calc-insert-result` doesn't insert the fully evaluated results, which are shown in the overlays. Here is an example:

```
a = 1
b = 1
c = a + b
d = b + c
e = c + d
```

The overlay shows fully evaluated, concrete results:
![image](https://user-images.githubusercontent.com/112426/83349891-623ecb80-a338-11ea-8af2-394388a68416.png)

while `literate-calc-insert-result` shows:
![image](https://user-images.githubusercontent.com/112426/83349913-83072100-a338-11ea-8dbe-971aeace5813.png)

I'm using Emacs 28.0.50 on macOS and literate-calc-mode 20200525.1416.

Please let me know if you need more details.

**Comment by sulami** [comment]
Oh yes, I see. I can probably publish a fix tomorrow, that’s an easy one I think.

**Comment by sulami** [comment]
I pushed a fix that seems to work for me. (I really need to get started
writing a test suite for this.)

Please let me know if this works for you, or if there are any remaining
issues.

**Comment by mpereira** [comment]
Works perfectly! Thanks for fixing it so quickly!
